version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: codesync
      POSTGRES_USER: codesync_user
      POSTGRES_PASSWORD: codesync_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codesync_user -d codesync"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass codesync_redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Uncomment the following service if you want to run the app with Docker
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgresql://codesync_user:codesync_password@postgres:5432/codesync
  #     - REDIS_URL=redis://:codesync_redis_password@redis:6379
  #     - NEXTAUTH_URL=http://localhost:3000
  #     - NEXTAUTH_SECRET=your-secret-key
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

volumes:
  postgres_data:
  redis_data: